PROJECT_NAME: 'dummy'


# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES_JSON: 'samples.json'

bam: False


# MACS parameters for peak calling
macs2_qvalue: 1e-5
macs2_qvalue_broad_cutoff: 1e-5
